### ISSUE TITLE
UxPlay only works when run with sudo

### ISSUE THREAD

**Issue by ioannis-vm** [antimof/UxPlay#130]
I've encountered an issue where UxPlay only works when I run it with sudo. When I run UxPlay without sudo, I receive the following error message:

```
UxPlay 1.63: An Open-Source AirPlay mirroring and audio-streaming server.
Required gstreamer plugin 'libav' not found
Missing plugin is contained in  '[GStreamer 1.x]-libav'
stopping
```

However, when I run UxPlay with sudo, it works without any issues. I've tried several troubleshooting steps, including installing the required GStreamer plugins, verifying file permissions, and building UxPlay from source. All the relevant files have the correct permissions, and my GStreamer installation is up-to-date.

System information:

- Operating System: Arch Linux x86_64
- Kernel Version: 6.2.6-arch1-1
- UxPlay Version: 1.63
- GStreamer Version: 1.22.1

Steps to reproduce:

- Install UxPlay and required GStreamer plugins.
- Run UxPlay without sudo.

Expected behavior:
- UxPlay should work without requiring sudo.

Actual behavior:
- UxPlay only works when run with sudo.

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by fduncanh** [comment]
see https://github.com/FDH2/UxPlay#4-gstreamer-issues-missing-plugins-etc

see also #129

**Comment by ioannis-vm** [comment]
Clearing the GStreamer cache resolved the issue.
`rm -rf ~/.cache/gstreamer-1.0/*`
I'm sorry I opened an issue on the wrong repo.
Thank you for your help!
