### ISSUE TITLE
Android screen share on raspberry pi?

### ISSUE THREAD

**Issue by myagizmaktav** [antimof/UxPlay#140]
If I don't have an apple product how I use this product?

**Comment by fduncanh** [comment]
Only apple's AirPlay protocol is supported.  Android uses a different one: GoogleCast.

**Comment by myagizmaktav** [comment]
Did we have an alternative for Google on raspi pi?

**Comment by fduncanh** [comment]
https://github.com/googlecast/CastReceiver
https://github.com/topics/chromecast-receiver
