### ISSUE TITLE
No gui window show up when I run uxplay

### ISSUE THREAD

**Issue by lipingliulp** [antimof/UxPlay#16]
When I run `$./uxplay`, nothing shows up. If I run `$GST_DEBUG=3 ./uxplay`, I get the following message. Any suggestions?

0:00:00.016992171 975557 0x55a209257240 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<video_source:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.021667555 975557 0x55a209257460 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<audio_source:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Initialized server socket(s)
*** WARNING *** The program 'uxplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

**Comment by lipingliulp** [comment]
For other users: another repo derived from this project works on my machine: 
https://github.com/wegank/ludimus

Absolutely have no intention to offend @antimof .

**Comment by phgod** [comment]
Try disabling your firewall (on the machine running uxplay) temporarily before connecting. If that works, then add a firewall rule to allow that particular ios device to connect.

**Comment by HiteshAI** [comment]
@lipingliulp thanks for your help. I had same problem and switched to ludimus and it works perfectly on Ubuntu 20.04

**Comment by pvillaverde** [comment]
Same issue here on 5.4.80-2-MANJARO.
Iphone does connect to the computer but nothing else happens, no sound or video displayed.

I've tryied ludimus but when I try to compile it, it doesn't find libplist.

**Comment by PaulMonnery** [comment]
@pvillaverde see the [wiki section](https://github.com/wegank/ludimus/wiki/Ludimus-on-Ubuntu#prerequisites) for ubuntu, you'll find packages for libplist, they should exist on manjaro too

**Comment by pvillaverde** [comment]
I already had it installed, but it doesn't find it when doing the make on the build folder. I tried even installing the libplist-git on the AUR repository but no success. I may try with ubuntu in the future and check if it outputs video or anything.

**Comment by mjbright** [comment]
I also managed to connect from iPad but no window opened.

I was about to try ludimus - I installed the build and run packages and the below page and tried uxplay one last time and it worked.  Thanks to @antimof and @wegank !!

https://github.com/wegank/ludimus/wiki/Ludimus-on-Ubuntu
