### ISSUE TITLE
Can the audio be directed to Bluetooth headphones or remain on the mobile phone?

### ISSUE THREAD

**Issue by fengzhuzhu** [antimof/UxPlay#165]
I want to only mirror the video while keeping the audio on my phone. I achieved the desired effect by modifying the Features to "0x4003C880", but I receive a "TEARDOWN" command after one minute. Please help me how to handle this, thank you!

**Comment by fduncanh** [comment]
see #166  and repost on the correct site.

your approach with features is the only way this might be possible (you want to stop the iOS device from cutting off audo when mirroring)


use uxplay -d to get some insight about the teardown request, and post your debug log if it is useful.

**Comment by fengzhuzhu** [comment]
Thank you very much @fduncanh
