### ISSUE TITLE
How to watch the stream?

### ISSUE THREAD

**Issue by malown** [antimof/UxPlay#2]
I successfully compiled the program, got it running and connected my iPhone. However I can't find any info on how to watch the stream. Some additional steps on how to use the program in the README would be useful

**Comment by scorpi11** [comment]
> I successfully compiled the program, got it running and connected my iPhone. However I can't find any info on how to watch the stream. Some additional steps on how to use the program in the README would be useful

uxplay only works as a screen mirror, not like a general AirPlay video sink. For the latter, there is no free software as far as I know.

**Comment by malown** [comment]
Then how do you show the mirror on screen?

**Comment by scorpi11** [comment]
It happens automatically as soon as you start screen mirroring.

**Comment by malown** [comment]
Oh, then it must be a bug, because I don‘t see anything. The program just says that a device connected and iPhone shows that it is mirroring the screen

**Comment by riseforrice** [comment]
same issue here....  I cannot see anything on my ubuntu 20.02, but the log shows everything works   fine.

**Comment by rcampbel3** [comment]
same issue on Ubuntu Studio 19.10... compiles fine, I start it, can connect, I see messages about connection, but no video

**Comment by wegank** [comment]
UxPlay works after installing gst-libav. Tested on Arch.

**Comment by nhusung** [comment]
I had some trouble getting this work, too. I’m using Ubuntu 20.04 with nvidia drivers and somehow the `autovideosink` does not show any output. However, `glimagesink` is working fine for me. So I simply changed it here:

https://github.com/antimof/UxPlay/blob/ed96d3f095c32ef7021f1dc9e986e28891baab5d/renderers/video_renderer_gstreamer.c#L47

I guess this issue is more related to the gstreamer/system graphics configuration than this application. But my solution might be a ‘temporary’ fix for others, too.

**Comment by antimof** [comment]
Yes, there's a problem with Nvidia nvdec and decodebin. Comparing to other HW accelerated decoders like VAAPI, decodebin cant corectly hadle nvdec and autovideosink combination. The only way to go is to  add glimagesink to gstreamer pipelene manualy, as you did.

**Comment by christianknauer** [comment]
Building was flawless, but for me no output was shown on a Lenovo X1 Carbon (Intel UHD 620) running Ubuntu 20 until I installed all of gstreamer as described, e.g., on https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

Now everything works as advertised. Great work, much appreciated!

**Comment by malown** [comment]
See the comment above this for a fix

**Comment by thalesmaoa** [comment]
> I had some trouble getting this work, too. I’m using Ubuntu 20.04 with nvidia drivers and somehow the `autovideosink` does not show any output. However, `glimagesink` is working fine for me. So I simply changed it here:
> 
> https://github.com/antimof/UxPlay/blob/ed96d3f095c32ef7021f1dc9e986e28891baab5d/renderers/video_renderer_gstreamer.c#L47
> 
> I guess this issue is more related to the gstreamer/system graphics configuration than this application. But my solution might be a ‘temporary’ fix for others, too.

I did as you suggested:

```
"queue ! decodebin ! videoconvert ! glimagesink name=video_sink sync=false", &error); 
```

But I get no output window.

**Comment by nhusung** [comment]
> But I get no output window.

Did you start the screen sharing on your mobile device? At least in my setup the window does not appear until then.

**Comment by thalesmaoa** [comment]
Yes! I did!

I can get it working now:
 1. Debug using ` GST_DEBUG=3 ./uxplay`
 2. It was claiming of missing H264 plugin.
 3. `sudo apt install libdvdnav4 libdvdread4 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libdvd-pkg`

**Comment by jeremy9959** [comment]
I made the glimagesink change as above, and I get a window mirroring my iphone, but the graphics are garbled.  I do have an NVIDIA video card in this machine.

**Comment by nhusung** [comment]
> I made the glimagesink change as above, and I get a window mirroring my iphone, but the graphics are garbled.  I do have an NVIDIA video card in this machine. 

I experienced some artifacts directly after establishing the connection as well.  For me, it helped to rotate my iPad back and forth once as each rotation changes the resolution of the video stream.  After that, everything worked reliably.

**Comment by jeremy9959** [comment]
No luck, alas.

--
Jeremy Teitelbaum, Ph.D.
Professor of Mathematics
University of Connecticut
341 Mansfield Road U-1009
Storrs, Connecticut 06269-1009
jeremy.teitelbaum@uconn.edu
http://teitelbaum.math.uconn.edu
________________________________

**Comment by littlewu2508** [comment]
I'm using kUbuntu 20.10 (groovy, development); one month ago everything about uxplay goes fine after `sudo apt install libdvdnav4 libdvdread4 gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libdvd-pkg`, but recently some packages updated, and uxplay cannot display the stream. Also libdvdread4 has no installation candidate

Here's my package versions of libdvd* : 
        ii  libdvd-pkg                                     1.4.2-1-1                                   all          DVD-Video playing library - installer
	ii  libdvdcss-dev:amd64                            1.4.2-1~local                               amd64        library for accessing encrypted DVDs - development files
	ii  libdvdcss2:amd64                               1.4.2-1~local                               amd64        library for accessing encrypted DVDs
	ii  libdvdnav4:amd64                               6.1.0-1build1                               amd64        DVD navigation library
	ii  libdvdread-dev:amd64                           6.1.1-2                                     amd64        library for reading DVDs (development)

**Comment by MartinPilu** [comment]
got nvidia card, for me the fix was to remove vaapi 
`sudo apt-get remove gstreamer1.0-vaapi`
