### ISSUE TITLE
Cannot share UxPlay window on video call apps

### ISSUE THREAD

**Issue by muonsei** [antimof/UxPlay#22]
The GUI works fine and is visible on my screen but whenever I try to share the UxPlay window on its own without sharing my entire screen, it doesn't appear on the options.

**Comment by cgraeser** [comment]
Have a look at #7 which describes a related problem. If you manually assign a window title as described there, it at least works to share from browsers.

**Comment by fduncanh** [comment]
THis is fiwith "ZOOMFIX" option in  updated UxPlay PR   #58
