### ISSUE TITLE
iPad doesn't detect UxPlay server.

### ISSUE THREAD

**Issue by Drahenios** [antimof/UxPlay#23]
I am runningUxPLay in Ubuntu 20.04.1 LTS. When I put the command ./uxplay on a terminal the following messages appear : 

Initialized server socket(s)
*** WARNING *** The program 'uxplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

This should be ok. However, if now I open "Screen Mirroring" on my iPad, it doesn't detect the UxPlay server.

**Comment by BjornPijnacker** [comment]
I can confirm having the same issue on `5.8.18-1-MANJARO` with `uxplay-git` from the AUR.

**Comment by Drahenios** [comment]
@BjornPijnacker Thet issue is still not resolved when I start the avahi-daemon service. In fact the daemon is already running. 

Perhaps this issue has something to do with the Wi-Fi not being 5G?

**Comment by UnlimitedCookies** [comment]
For me `systemctl start avahi-daemon` solved it. Perhaps this should be mentioned in the README.

Further, the AUR is missing quite some dependencies (avahi, cmake (make dep))

**Comment by Drahenios** [comment]
I confirm the issue is now solved nad UxPlay works perfectly. The problem was that I couldn't manage to get "exactly" the same WiFi connection on my two devices since I was using a public WiFi. Thank you for your comments.
