### ISSUE TITLE
iPad unable to connect

### ISSUE THREAD

**Issue by denishem** [antimof/UxPlay#24]
Hi.
I was using uxplay for a while without issues on Manjaro but yesterday I was suddenly unable to connect to the server from my iPad. 

The console doesn't show anything appart from the avahi warnings. I tried turning on debugging but still nothing. Tried to restart avahi-daemon, nothing.

The iPad sees the server but when selected it just loads indefinitely and then says it's unable to connect.

There was a recent xorg update on Manjaro, maybe that's the problem? 

Thanks

**Comment by denishem** [comment]
Nevermind, it was a firewall issue!

**Comment by hakanyi** [comment]
Would you mind sharing how you solved the issue, @denishem? Thanks!
