### ISSUE TITLE
Multiple streaming devices support

### ISSUE THREAD

**Issue by sskorol** [antimof/UxPlay#39]
Hi, I tried this app and it works great for a single device. However, when I try to stream from 2 apple devices in parallel, seems like streams just overlap each other within the same window. Noticed the same issue on RPiPlay as well. Is there any way to run multiple streams?

OS: Ubuntu 20.04
Apple devices: iPhone and iPad

**Comment by fduncanh** [comment]
there is an updated release of UxPlay at pr #58 that includes a  -m (random MAC address) option that allows two or more instances of UxPlay to coexist.

But it you are streaming video, there is a lot of latency.

**Comment by sskorol** [comment]
@fduncanh thanks! I built it from your master branch and it works well with 2 apple devices so far.
