### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ice-kylin** [antimof/UxPlay#46]
# Unable to connect

> Unable to connect and iPad can't find it

## Info

- Laptop: Arch Linux x86_64
- iPad: iPadOS 14.4.2

![Konsole](https://user-images.githubusercontent.com/56141162/115860175-b7f5f800-a463-11eb-8634-10696f3c6ae6.png)

![iPad](https://user-images.githubusercontent.com/56141162/115862638-f4772300-a466-11eb-80f9-7d80c74dca39.png)

I tried the ways below, but it still didn't work:

1. Turn off the firewall
2. Make sure my iPad and laptop connected to the same 5GHz WiFi
3. Try using the self compiled version and the version in the `Arch User Repository`
4. No proxy used

The only hint I get is output from Konsole but I don't know how to fix it.

I would be very grateful if the developer could provide a solution.

Thanks!

**Comment by D3SOX** [comment]
Do you have the `avahi-daemon` service started? `systemctl status avahi-daemon.service`

**Comment by ice-kylin** [comment]
> Do you have the `avahi-daemon` service started? `systemctl status avahi-daemon.service`.
> Works fine for me using my AUR package + iPadOS 14.3

![image](https://user-images.githubusercontent.com/56141162/115868267-c695dc80-a46e-11eb-821c-f2d2cc78e4ed.png)

I checked that `avahi-daemon` service didn't started so I started it and it works.

Thanks for your help!
