### ISSUE TITLE
Screen Mirroring is blurry on 5Ghz wifi

### ISSUE THREAD

**Issue by redromnon** [antimof/UxPlay#54]
I am using Pop OS 20.10. My iPad is successfully being mirrored to my laptop, but the only thing that troubles me a little is the quality. The iPad screen is looking blurry despite using a 5Ghz Wifi network.

Is there something I can do? Is it because of my network?

**Comment by ottersity** [comment]
For me the screen is even blurry if i connect my ipad with usbc to lan and connect to my pc on lan. So the network capacity / traffic shouldn't be the problem.

**Comment by ottersity** [comment]
If you change line 143 of lib/raop_handlers.h from
`plist_t displays_0_overscanned_node = plist_new_bool(1);`
to
`plist_t displays_0_overscanned_node = plist_new_bool(0);`

The screen is less blurry.

**Comment by redromnon** [comment]
Yeah the quality is definitely improved, thanks!
