### ISSUE TITLE
Connection via USB instead of Wi-Fi

### ISSUE THREAD

**Issue by ka2o** [antimof/UxPlay#6]
This software is very useful. However, due to the bandwidth it requires, it would be extremely useful if sharing could also be done via USB cable. Are there any prospects for making this work?

**Comment by antimof** [comment]
It's up to your operating system. UxPlay is application level software that knows nothing about underlying OS.

**Comment by antimof** [comment]
You can teether your USB cable as network connection...

**Comment by chronchi** [comment]
I'm sorry for commenting here, but how would one do that if the ipad, for example, has no tethering option on the settings. I tried googling for this but I couldn't find anything.
