### ISSUE TITLE
make error: stdlib.h not found

### ISSUE THREAD

**Issue by BraveSentry** [antimof/UxPlay#64]
This is what I get at the end of `make`

```
[ 98%] Building CXX object CMakeFiles/uxplay.dir/uxplay.cpp.o
In file included from /usr/include/c++/9/ext/string_conversions.h:41,
                 from /usr/include/c++/9/bits/basic_string.h:6493,
                 from /usr/include/c++/9/string:55,
                 from /mnt/044A4C273A322D33/Downloads/UxPlay-master/uxplay.cpp:24:
/usr/include/c++/9/cstdlib:75:15: fatal error: stdlib.h: Datei oder Verzeichnis nicht gefunden
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/uxplay.dir/build.make:63: CMakeFiles/uxplay.dir/uxplay.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:206: CMakeFiles/uxplay.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

```

This is on Mint 20.2 Cinnamon. Any other system info needed?

**Comment by fduncanh** [comment]
this is  nothing to do with uxplay: your c++ compiler seems not to be  correctly installed.   <stdlib.h> is missing!

Note: The current version of UxPlay is at http://github/com/FDH2/UxPlay

**Comment by BraveSentry** [comment]
Thank you!
Just in case anyone else trips over that: Replacing "include_next" with "include" in the file(s)* mentioned in the error log(s)* helps, cf [here](https://gcc.gnu.org/legacy-ml/gcc/2016-05/msg00003.html)

*I had the same error concerning a different file, so there may be more places to fix this.
