### ISSUE TITLE
Apple TV is not showing!

### ISSUE THREAD

**Issue by kreimben** [antimof/UxPlay#68]
Hi guys. always thanks about your contributions though, I can mirror almost of app in my ipad and iphone EXCEPT Apple TV.

Whenever I play any serices of apple original, mirroring is stopped.

Is that problem of Apple? (prevent mirroring not real apple devices or something...)

Please help me :)

**Comment by fduncanh** [comment]
1. Uxplay is not maintained here any longer, updates (UxPlay 1.42) are  at http://github.com/FDH2/UxPlay

2.  I think you are right, Apple  DRM  (as in Apple TV) will not get decrypted by UxPlay.

**Comment by kreimben** [comment]
Ok, Thanks. I didn't find repository correctly :/
