### ISSUE TITLE
Window freezing after some time

### ISSUE THREAD

**Issue by LorenzBung** [antimof/UxPlay#69]
Hi,
compilation and running on Ubuntu 20.04 work fine for me and I can share my screen from an iPad (8. Generation).
However, after a few minutes or even seconds, the window freezes and I have to restart the application and screen share.
Is this a known issue, and how can it be fixed?

**Comment by fduncanh** [comment]
Uxplay is no longer maintained here.

UxPlay 1.42 is available at https://github.com/FDH2/UxPlay

If you still have your issue with UxPlay1.42, post your issue there

**Comment by LorenzBung** [comment]
@fduncanh Ahh, thanks for the update. It would probably be a good idea to state that in the README.md in this repo and link to the newer one, because a lot of people will only find this version and stick to it.

I will try out UxPlay 1.42 and see if the issue persist, and if so, open a new issue on https://github.com/FDH2/UxPlay.
