### ISSUE TITLE
UxPlay start on boot

### ISSUE THREAD

**Issue by abdullahaltun70** [antimof/UxPlay#71]
Is there any way to start uxplay automatically on boot? 
I am running Ubuntu 21.10.

**Comment by fduncanh** [comment]
Difficult:  the Bounjour (dns-sd)  service detection doesnt seem to work (for me)  if the client isnt already looking for a connection when UxPlay is started.     (Maybe my dns-sd setup is not right, I dont understand the problem).    The uxplay -t <n> option is designed to deal with that, but right now only starts the timer after at least one connection has been made.
