### ISSUE TITLE
BUG: Illegal instruction when start

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [antimof/UxPlay#73]
machine: manjaro linux 5.14.21-2
when I install uxplay and start it, i have the follow error:

> ~> uxplay
> using system MAC address 90:78:41:**:**:**
> Initialized server socket(s)
> fish: Job 1, 'uxplay' terminated by signal SIGILL (Illegal instruction)

I try to stop firewall, but not work.

**Comment by yagueto** [comment]
As per https://github.com/antimof/UxPlay/issues/69#issuecomment-987613773, UxPlay is no longer maintained here, but at [FDH2/UxPlay](https://github.com/FDH2/UxPlay). They can probably help you there
