### ISSUE TITLE
UxPlay crashes randomly after some time

### ISSUE THREAD

**Issue by All3xJ** [antimof/UxPlay#77]
```
X Error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 20 (X_GetProperty)
Resource id in failed request: 0x121aa56
Serial number of failed request: 364789
Current serial number in output stream: 364789
```

![image](https://user-images.githubusercontent.com/20903913/151071260-b06ededb-d731-4e26-a5fa-ef9148953afa.png)

I am under ArchLinux KDE Plasma. The bug seems to only happen under Xorg, not wayland

**Comment by fduncanh** [comment]
Development of UxPlay is now at https://github.com/FDH2/UxPlay
get latest version 1.46 there and post any issues there.

**Comment by All3xJ** [comment]
> Development of UxPlay is now at https://github.com/FDH2/UxPlay get latest version 1.46 there and post any issues there.

yeah it happens in that version too.

**Comment by fduncanh** [comment]
I see you are using Arch.    are you compiling from github, or are you using a  package from AUR?
Is your issue the same as

https://github.com/FDH2/UxPlay/issues/56

If you cant fix it  open your issue on the new site.

**Comment by fduncanh** [comment]
But probably a gstreamer plugin issue?
See Troubleshooting,      Usually this is the vaapi or glimagesink plugin not working with your hardware, being selected by default.
 try  explicitly choosing the videosink: "uxplay -vs xvimagesink" (or ximagesink)

**Comment by All3xJ** [comment]
The bug seems gone

**Comment by fduncanh** [comment]
If is was an arch  AUR package, there was a fix involving a compiler CFLAG.
