### ISSUE TITLE
Start UxPlay as a Service

### ISSUE THREAD

**Issue by monomycelium** [antimof/UxPlay#92]
I am quite the newbie when we're at desktop environments in Linux. I envision a seamless future where I could start UxPlay remotely, preferably using a Linux service or SSH. Nothing appears on the desktop environment, PIXEL on a Raspberry Pi 4, when I run this through SSH:

```
uxplay -n Mycelium -nh
```

Instead, my Macintosh disconnects from the AirPlay server. I know this is because the command was not meant to be run remotely. This is an extract of the output:

```
GStreamer error: GStreamer encountered a general resource error.
Removing connection for socket 32
Destroying connection
Open connections: 1
raop_rtp_mirror->running is no longer true
Removing connection for socket 34
Destroying connection
```

I would appreciate it if you would render me support to start UxPlay without accessing the desktop environment.

If you wondered why I did not use the `-rpi` option, the streaming is laggier than without using the option.

**Comment by fduncanh** [comment]
see https://github.com/antimof/UxPlay/issues/91

**Comment by monomycelium** [comment]
Thank you for that swift response! Is there a way I can start UxPlay as a Linux service or start it automatically?

**Comment by fduncanh** [comment]
See issue #59 on the new UxPlay site mentioned above

https://github.com/FDH2/UxPlay/issues/#59
